use syn::visit::Visit;

/// A prelude entry extracted from source.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct PreludeEntry {
    pub variant_name: String,
    pub lisp_name: String,
    pub source: Option<String>,
}

/// Visitor that finds prelude-related structures.
pub struct PreludeExtractor {
    pub entries: Vec<PreludeEntry>,
}

impl PreludeExtractor {
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
        }
    }
}

impl<'ast> Visit<'ast> for PreludeExtractor {
    fn visit_item_struct(&mut self, node: &'ast syn::ItemStruct) {
        if node.ident == "PreludeEntry" {
            // Found the struct definition - entries are generated by macro
            // so we need a different approach
        }
        syn::visit::visit_item_struct(self, node);
    }

    fn visit_item_static(&mut self, node: &'ast syn::ItemStatic) {
        // Look for static PreludeEntry definitions like:
        // static _PRELUDE_0: PreludeEntry = PreludeEntry { name: "map", source: "..." };
        let name_str = node.ident.to_string();
        if name_str.starts_with("_PRELUDE_") || name_str == "PRELUDE_ALL" {
            // These are generated by macro, so we won't find them in source
        }
        syn::visit::visit_item_static(self, node);
    }
}

/// Extract prelude entries from .grift file content.
pub fn extract_from_grift(content: &str) -> Vec<PreludeEntry> {
    let mut entries = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(stripped) = trimmed.strip_prefix("(fn!") {
            // Parse: (fn! name (params...) body...)
            let rest = stripped.trim_start();
            if let Some(space_pos) = rest.find(|c: char| c.is_whitespace() || c == '(') {
                let name = &rest[..space_pos];
                entries.push(PreludeEntry {
                    variant_name: name.to_string(),
                    lisp_name: name.to_string(),
                    source: Some(trimmed.to_string()),
                });
            }
        }
    }
    entries
}
