[workspace]
resolver = "2"
members = [
    "crates/grift_arena",
    "crates/grift_macros",
    "crates/grift_core",
    "crates/grift_parser",
    "crates/grift_eval",
    "crates/grift_repl",
    "crates/grift",
    "crates/grift_arena_embedded",
]

[workspace.package]
version = "1.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
