[package]
name = "grift_repl"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "REPL for the grift Lisp language"

[[bin]]
name = "grift"
path = "src/main.rs"

[[bin]]
name = "grift-bench"
path = "src/bench.rs"

[[example]]
name = "vec_storage"
path = "examples/vec_storage.rs"

[dependencies]
grift_arena = { version = "0.1.1", path = "../grift_arena", features = ["std"] }
grift_parser = { version = "0.1.1", path = "../grift_parser" }
grift_eval = { version = "0.1.1", path = "../grift_eval" }
grift_arena_embedded = { version = "0.1.1", path = "../grift_arena_embedded" }
