[package]
name = "grift_repl"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "REPL for the Grift Scheme language"
repository = "https://github.com/gold-silver-copper/grift"
documentation = "https://docs.rs/grift_repl"
keywords = ["repl", "lisp", "scheme", "interpreter"]
categories = ["development-tools", "command-line-utilities"]

[[bin]]
name = "grift"
path = "src/main.rs"
doc-scrape-examples = false

[[bin]]
name = "grift-bench"
path = "src/bench.rs"
doc-scrape-examples = false

[dependencies]
grift_arena = { workspace = true }
grift_core = { workspace = true, features = ["all-libraries"] }
grift_parser = { workspace = true }
grift_eval = { workspace = true }
grift_arena_embedded = { workspace = true }
grift_std = { workspace = true }
rustyline = { version = "17.0.2", features = ["derive"] }

[package.metadata.docs.rs]

[[example]]
name = "load_file"
doc-scrape-examples = false

[[example]]
name = "native_interop"
doc-scrape-examples = false

[[example]]
name = "embedded_hardware"
doc-scrape-examples = false
