//! Zero-arena-cost prelude types and generated entries.
//!
//! [`PreludeEntry`] holds a binding name and its combiner source text in
//! static (`&'static str`) memory — no arena slots are consumed until
//! the function is actually invoked.
//!
//! [`Prelude`] is a thin `Copy` wrapper used as a [`Value`](crate::Value)
//! variant. When the evaluator encounters a `Prelude` value during
//! application, it parses and evaluates the source on demand.
//!
//! The proc macro [`grift_macros::include_prelude!`] reads `prelude.grift`
//! at compile time and generates:
//! - Static `PreludeEntry` values for each lazy prelude binding
//! - The `PRELUDE_ALL` array referencing those entries
//! - An `init_prelude_constants` function for numeric/boolean/string constants

use crate::native::LispOps;

/// A single prelude entry: name + combiner source in static memory.
#[derive(Debug)]
pub struct PreludeEntry {
    /// The Lisp-visible name of the function (e.g. `"map"`).
    pub name: &'static str,
    /// Source text parsed on demand (e.g. `"(lambda (f xs) ...)"` ).
    pub source: &'static str,
}

/// A prelude function reference (Copy, 'static, one pointer).
#[derive(Clone, Copy, Debug)]
pub struct Prelude(pub &'static PreludeEntry);

impl PartialEq for Prelude {
    /// Compare prelude handles by entry identity.
    ///
    /// Prelude values are thin wrappers around `'static` entry pointers, so
    /// pointer equality is the canonical equality relation.
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self.0, other.0)
    }
}
impl Eq for Prelude {}

impl Prelude {
    /// Create a new `Prelude` reference from a static entry.
    pub const fn new(entry: &'static PreludeEntry) -> Self {
        Self(entry)
    }
    /// The Lisp-visible function name.
    pub const fn name(&self) -> &'static str {
        self.0.name
    }
    /// The source text, parsed on first invocation.
    pub const fn source(&self) -> &'static str {
        self.0.source
    }
    /// True when this entry's source expands to a raw operative.
    pub(crate) fn is_operative(&self) -> bool {
        self.source().trim_start().starts_with("(vau")
    }
}

// Generated by the proc macro: static PreludeEntry values, PRELUDE_ALL array,
// and startup helpers for constants.
#[allow(missing_docs)]
mod _prelude_generated {
    use super::*;
    grift_macros::include_prelude!("prelude.grift");
}
pub use _prelude_generated::*;
