//! Zero-arena-cost standard library types and generated entries.
//!
//! [`StdLibEntry`] holds a function name and its lambda source text in
//! static (`&'static str`) memory — no arena slots are consumed until
//! the function is actually invoked.
//!
//! [`StdLib`] is a thin `Copy` wrapper used as a [`Value`](crate::Value)
//! variant. When the evaluator encounters a `StdLib` value during
//! application, it parses and evaluates the source on demand.
//!
//! The proc macro [`grift_macros::include_stdlib!`] reads `prelude.grift`
//! at compile time and generates:
//! - Static `StdLibEntry` values for each `(define! (fn …) …)` form
//! - The `STDLIB_ALL` array referencing those entries
//! - An `init_stdlib_constants` function for numeric/boolean/string constants

use crate::lisp::Lisp;

/// A single standard library entry: name + lambda source in static memory.
#[derive(Debug)]
pub struct StdLibEntry {
    /// The Lisp-visible name of the function (e.g. `"map"`).
    pub name: &'static str,
    /// Lambda source text parsed on demand (e.g. `"(lambda (f xs) ...)"` ).
    pub source: &'static str,
}

/// A standard library function reference (Copy, 'static, one pointer).
#[derive(Clone, Copy, Debug)]
pub struct StdLib(pub &'static StdLibEntry);

impl PartialEq for StdLib {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self.0, other.0)
    }
}
impl Eq for StdLib {}

impl StdLib {
    /// Create a new `StdLib` reference from a static entry.
    pub const fn new(entry: &'static StdLibEntry) -> Self {
        Self(entry)
    }
    /// The Lisp-visible function name.
    pub const fn name(&self) -> &'static str {
        self.0.name
    }
    /// The lambda source text, parsed on first invocation.
    pub const fn source(&self) -> &'static str {
        self.0.source
    }
}

// Generated by the proc macro: static StdLibEntry values, STDLIB_ALL array,
// and init_stdlib_constants function.
#[allow(missing_docs)]
mod _stdlib_generated {
    use super::*;
    grift_macros::include_stdlib!("prelude.grift");
}
pub use _stdlib_generated::*;
