//! Zero-arena-cost standard library types and generated entries.
//!
//! [`StdLibEntry`] holds a name and lambda source in static memory.
//! [`StdLib`] is a thin wrapper used as a [`Value`] variant.
//! The proc macro [`grift_macros::include_stdlib!`] generates the
//! static entries from `prelude.grift` at compile time.

use crate::lisp::Lisp;

/// A single standard library entry: name + lambda source in static memory.
#[derive(Debug)]
pub struct StdLibEntry {
    pub name: &'static str,
    pub source: &'static str,
}

/// A standard library function reference (Copy, 'static, one pointer).
#[derive(Clone, Copy, Debug)]
pub struct StdLib(pub &'static StdLibEntry);

impl PartialEq for StdLib {
    fn eq(&self, other: &Self) -> bool {
        core::ptr::eq(self.0, other.0)
    }
}
impl Eq for StdLib {}

impl StdLib {
    pub const fn new(entry: &'static StdLibEntry) -> Self {
        Self(entry)
    }
    pub const fn name(&self) -> &'static str {
        self.0.name
    }
    pub const fn source(&self) -> &'static str {
        self.0.source
    }
}

// Generated by the proc macro: static StdLibEntry values, STDLIB_ALL array,
// and init_stdlib_constants function.
grift_macros::include_stdlib!("prelude.grift");
