[package]
name = "grift_core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core types and Lisp context for the Grift Scheme language"
repository = "https://github.com/gold-silver-copper/grift"
documentation = "https://docs.rs/grift_core"
keywords = ["types", "lisp", "scheme", "no_std", "embedded"]
categories = ["no-std", "data-structures", "embedded"]

[dependencies]
grift_arena = { version = "1.2.0", path = "../grift_arena" }
grift_macros = { version = "1.2.0", path = "../grift_macros" }
