[package]
name = "grift_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lisp parser for the Grift Scheme language"
repository = "https://github.com/gold-silver-copper/grift"
documentation = "https://docs.rs/grift_parser"
keywords = ["parser", "lisp", "scheme", "no_std", "embedded"]
categories = ["no-std", "parsing", "embedded"]

[dependencies]
grift_arena = { workspace = true }
grift_macros = { workspace = true }
grift_core = { workspace = true }
libm = "0.2"
