[package]
name = "grift_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lisp parser for the Grift Scheme language"
repository = "https://github.com/gold-silver-copper/grift"
documentation = "https://docs.rs/grift_parser"
keywords = ["parser", "lisp", "scheme", "no_std", "embedded"]
categories = ["no-std", "parsing", "embedded"]

[features]
default = ["all-libraries"]
all-libraries = [
    "scheme-base", "scheme-case-lambda", "scheme-char", "scheme-complex",
    "scheme-cxr", "scheme-eval", "scheme-file", "scheme-inexact",
    "scheme-lazy", "scheme-load", "scheme-process-context", "scheme-r5rs",
    "scheme-read", "scheme-repl", "scheme-time", "scheme-write",
    "srfi-64",
]
scheme-base = []
scheme-case-lambda = []
scheme-char = []
scheme-complex = []
scheme-cxr = []
scheme-eval = []
scheme-file = []
scheme-inexact = []
scheme-lazy = []
scheme-load = []
scheme-process-context = []
scheme-r5rs = []
scheme-read = []
scheme-repl = []
scheme-time = []
scheme-write = []
srfi-64 = []

[dependencies]
grift_arena = { workspace = true }
grift_macros = { workspace = true }
grift_core = { workspace = true }
libm = "0.2"
