[package]
name = "grift_eval"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lisp evaluator for the Grift Scheme language"
repository = "https://github.com/gold-silver-copper/grift"
documentation = "https://docs.rs/grift_eval"
keywords = ["evaluator", "lisp", "scheme", "no_std", "embedded"]
categories = ["no-std", "development-tools", "embedded"]

[dependencies]
grift_arena = { workspace = true }
grift_parser = { workspace = true }
libm = "0.2"
icu_casemap = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_properties = { version = "2.1", default-features = false, features = ["compiled_data"] }
icu_locale_core = { version = "2.1", default-features = false }

[dev-dependencies]
grift_std = { workspace = true }
