[package]
name = "grift"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "A simple minimalistic Lisp with a built-in arena allocator"

[features]
repl = ["dep:rustyline"]

[dependencies]
grift_macros = { path = "../grift_macros" }
rustyline = { version = "17.0.2", optional = true }

[[bin]]
name = "grift"
required-features = ["repl"]
